#! /bin/bash

set -eux


sudo DEBIAN_FRONTEND=noninteractive apt update
sudo DEBIAN_FRONTEND=noninteractive apt install -y gh fzf tmux zsh s3cmd file

curl -sS https://starship.rs/install.sh | sudo sh -s -- -y
sudo chsh -s /bin/zsh coder
