#! /bin/bash

set -eux


sudo DEBIAN_FRONTEND=noninteractive apt update
sudo DEBIAN_FRONTEND=noninteractive apt install -y gh tmux zsh s3cmd file

curl -sS https://starship.rs/install.sh | sudo sh -s -- -y
sudo chsh -s /bin/zsh coder
sudo chown -R coder:coder /home/ygiannaris
sudo chmod -R u+rwx /home/ygiannaris
sudo chmod -R g+rwx /home/ygiannaris
# install vault
wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(grep -oP '(?<=UBUNTU_CODENAME=).*' /etc/os-release || lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
sudo apt update
sudo apt install vault || echo "vault install expected to fail"
