#! /bin/bash

set -eux


sudo DEBIAN_FRONTEND=noninteractive apt update
sudo DEBIAN_FRONTEND=noninteractive apt install -y gh fzf tmux zsh s3cmd file

curl -sS https://starship.rs/install.sh | sudo sh -s -- -y
sudo chsh -s /bin/zsh coder
sudo chown -R coder:coder /home/ygiannaris
sudo chmod -R u+rwx /home/ygiannaris
sudo chmod -R g+rwx /home/ygiannaris
